name: Run search_module.py

on:
  push:
    paths:
      - 'search_module.py'
      - 'requirements.txt'
      - '.github/workflows/**'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run search_module.py
        run: python search_module.py