name: Run search_module.py

on:
  push:
    paths:
      - 'search_module.py'
      - 'requirements.txt'
      - '.github/workflows/**'

jobs:
  run-script:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run search_module.py
        run: python search_module.py
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull origin main --rebase
          git add .
          # 변경 사항이 있을 때만 커밋
          if ! git diff --staged --quiet; then
            git commit -m "update push information (${{ env.TODAY }})"
            git pull --rebase
            git push
          else
            echo "변경 사항이 없어 커밋하지 않습니다."
          fi